### ISSUE TITLE
How to use certificate-generator to create certificates

### ISSUE THREAD

**Issue by Elvisonyedika** [zedomel/certificate-generator#1]
Hello,

Thanks for this beautiful work.

However, I could not find a section describing how to use this project in creating custom certificate. 

I will so much appreciate if you can help me with this.

Thanks in anticipation.

**Comment by zedomel** [comment]
Hello @Elvisonyedika ,

I'm preparing a documentation and a new version of certificate-generator. Currently, I'm finishing a GUI to allow customize the certificates.

But if could not wait, I can help you setting things up. Let me know, what you need.

thanks.

**Comment by Xees** [comment]
Dear,

Any update on this certificate generator?

It's an awesome tool to add on websites. And sadly i cannot find any online solution available that would fit my situation.

**Comment by zedomel** [comment]
Hi @Xees ,

unfortunately I could not work on the new version of this generator. I'm working on another project, but as I finished it I will come back to this generator again. 

Can you describe your needs so I can have a feedback and make the version more suitable for other users too?

Thank you.

**Comment by zedomel** [comment]
Hi @Xees, 

please if your still interest take a look of the new version of this certificate generator (v.2.0).

If you need any help, please tell me what I can do for you.

thanks.
